minor: tasl/module6-task1 edit hocs
htmlacademy-react/573447-six-cities-5 pull request #10
Opened 2020-10-24 11:35 UTC by What1s1ove

2020-10-26 17:49 UTC, DmitryMarkov requested changes
Задание выглядит недоделанным.

-  не вынесен стейт из `offer-screen.jsx` и `main-screen.jsx`

Кроме того, не видно оптимизаций (п.2), например, при выборе города или сортировки перерисовывается заголовок

2020-10-26 17:49 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  const [currentLocation, setCurrentLocation] = React.useState(getDefaultLocation(locations));
> Избавьтесь от внутреннего стейта в компонентах — перенесите стейт в компоненты высшего порядка (HOC)

2020-10-26 17:49 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  const [currentLocation, setCurrentLocation] = React.useState(getDefaultLocation(locations));
в `offer-screen.jsx` тоже

2020-10-28 10:12 UTC, What1s1ove commented on src/components/main-screen/main-screen.jsx
> +  const [currentLocation, setCurrentLocation] = React.useState(getDefaultLocation(locations));
<img width="1028" alt="изображение" src="https://user-images.githubusercontent.com/42296182/97422561-a39ecb80-1916-11eb-8b09-7196eafe4d99.png">
Обязательно выносить стейт в ХОКи нужно только если используешь класс-компоненты

2020-10-28 10:26 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  const [currentLocation, setCurrentLocation] = React.useState(getDefaultLocation(locations));
Смысла тогда не вижу в этом задании... Зачем все переносить в хоки, а потом в хуки, если принципиально стейт класс-компонента не отличается от хука useState

2020-10-28 10:52 UTC, What1s1ove commented on src/components/main-screen/main-screen.jsx
> +  const [currentLocation, setCurrentLocation] = React.useState(getDefaultLocation(locations));
Просто по идее, про хуки мы знать ещё не должны)

2020-10-28 11:02 UTC, merged