minor: task.module7-task3 add load data for the offer screen functionality
htmlacademy-react/573447-six-cities-5 pull request #14
Opened 2020-11-01 09:20 UTC by What1s1ove

2020-11-03 09:27 UTC, DmitryMarkov requested changes
По коду вопросов нет, не реализована функциональность ТЗ:

> На страницу выводится не больше 10 отзывов.

> Отзывы должны быть отсортированы от новых к старым (новые сверху).

> Форма отправки отзыва отображается только для авторизованных пользователей.

> Текст отзыва должен содержать от 50 до 300 символов.

> Пока пользователь не выбрал оценку и не ввёл текст допустимой длины, кнопка отправки отзыва не активна.

> При нажатии кнопки «Submit» и отправки данных форма должна блокироваться. Разблокировка формы происходит в случае успешной отправки или при возникновении ошибки.

> В случае успешной отправки отзыва форма очищается.

> В случае возникновения ошибки следует уведомить пользователя. Способ отображения ошибки остаётся на усмотрение разработчика.

2020-11-03 09:27 UTC, DmitryMarkov commented on src/common/enums/action-type.enum.js
> +const PlaceActionType = {
Почему Place, если это Offer?

2020-11-03 09:27 UTC, DmitryMarkov commented on src/services/api/api.js
> +        const isWhiteRoute = checkIsWhiteRoute(config.url, unauthorizedWhiteRoutes);
это нетолерантно :))
ну, и лучше проверять на приватность

2020-11-03 09:32 UTC, DmitryMarkov commented on src/common/enums/action-type.enum.js
> +const PlaceActionType = {
Ну или hotel, на крайний случай

2020-11-03 16:25 UTC, What1s1ove commented on src/common/enums/action-type.enum.js
> +const PlaceActionType = {
У меня есть редьюсер/экшен-тайп с именем `PlacesData`, который хранит список офферов
Хотел что бы было единообразно

2020-11-03 16:27 UTC, What1s1ove commented on src/services/api/api.js
> +        const isWhiteRoute = checkIsWhiteRoute(config.url, unauthorizedWhiteRoutes);
На беке, как я мог наблюдать, обычно делают масив с "белыми" роутами, на который можно ходить, например, без токена
Белые роуты проще описать, тк их обычно в разы меньше чем обычных

2020-11-04 20:48 UTC, DmitryMarkov approved these changes
отличное решение

2020-11-04 20:48 UTC, DmitryMarkov commented on src/components/review-form/review-form.jsx
> +  offerId: PropTypes.number.isRequired,
тут ошибка в пропсах

![image](https://user-images.githubusercontent.com/9193608/98166153-0afce280-1ef8-11eb-8b66-1b548e073718.png)

2020-11-04 20:48 UTC, merged