minor: task/module5-task1 add redux to the app & simple change location functionality
htmlacademy-react/573447-six-cities-5 pull request #8
Opened 2020-10-19 18:00 UTC by What1s1ove

2020-10-21 11:51 UTC, DmitryMarkov requested changes
Задание недоделано. Необходимо добавить моки для хотя бы еще одного города, чтобы проверить работу переключения и выборки городов. Пункт 7 ДЗ

2020-10-21 11:51 UTC, DmitryMarkov commented on src/components/main-screen/main-screen.jsx
> +  offers: offersState.offers,
такие вещи указывают на проблемы с неймингом

2020-10-22 07:24 UTC, DmitryMarkov approved these changes
В целом, хорошо, но есть недочет:

> Не забудьте обновлять заголовок с количеством предложений, доступных для выбранного города. Например: 312 places to stay in Amsterdam

![image](https://user-images.githubusercontent.com/9193608/96838494-a437ed80-1450-11eb-904f-ea4d36c52dde.png)

Упс...

Ну и я бы не делал меню городов рандомным порядком, мельтешит :)

2020-10-22 07:24 UTC, DmitryMarkov commented on src/components/favorites-screen/favorites-screen.jsx
> +        <a className="footer__logo-link" href="main.html">
ссылку на главную можно сделать через Link

2020-10-22 07:24 UTC, merged

2020-10-22 07:29 UTC, What1s1ove commented on src/components/favorites-screen/favorites-screen.jsx
> +        <a className="footer__logo-link" href="main.html">
Не можно, а нужно) К это еще не дошел

Спасибо за напоминание об обновлении заголовка. Почему-то обратил внимание только на количество офферов, а сам город не заметил

Оки, добавлю сортировку городов